---
name: module3_task4

on:
  push:
    branches:
      - "main"
      - "master"
    tags:
      - "v*.*.*"

  pull_request:
    types: [opened, reopened, edited, ready_for_review]

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate setup.sh script
        run: shellcheck module3_task4/setup.sh

      - name: Setup required tools
        run: source module3_task4/setup.sh

      - name: Lint markdown files
        run: |
          cd module3_task4
          make lint

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.42.1
          working-directory: module3_task4

      - name: Build the app
        run: |
          cd module3_task4
          make build

      - name: Run tests and validation
        run: |
          cd module3_task4
          make test

      - name: Package the app
        run: |
          cd module3_task4
          make package

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md

      - name: 1.0.0
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          token: ${{ secrets.PAT }}
