---
name: module3_task2

on:
  push:
    branches:
      -main
      -master

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate setup.sh script
        run: shellcheck module3_task2/setup.sh

      - name: Setup required tools
        run: source module3_task2/setup.sh

      - name: Build the app
        run: |
          cd module3_task2
          make build

      - name: Package the app
        if: ${{ success() && github.ref == 'refs/head/main' }}
        run: |
          cd module3_task2
          make package

      - name: Archive artifact
        if: ${{ success() && github.ref == 'refs/head/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: module3_task2/awesome-website.zip
